version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Port mapping for the frontend service
    depends_on:
      - backend  # Dependence on the backend service

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Port mapping for the backend service

# Define any additional services, networks, or volumes if needed
# ...
