- hosts: all
  become: true
  tasks:
    - name: Installing apache2
      apt:
        name: apache2
        state: present
      notify:
        - starting apache2 service

  handlers:
    - name: starting apache2 service
      service:
        name: apache2 
        state: started
    
