- hosts: all
  become: true
  tasks:
    - name: Installing apache2
      apt:
        name: apache2
        state: present
      register: out 

    - name: starting apache2 service
      service:
        name: apache2 
        state: started
      when: out.changed == True
